
cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: 
      secret-key: 
    end-point: 
      uri: https://sqs.us-east-2.amazonaws.com/227471887092/SpringBootSQSExample

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: SpringBootSQSExample
          content-type: text/plain # messages by default have contentType header set to application/json
        customOutput:
          destination: https://sqs.us-east-2.amazonaws.com/227471887092/SpringBootSQSExample
